# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bd643f7eada79abcc3919504763cf885acef06dd9f5ef87a08024eee050e785136d6cd6b79a48765383ccc3edb30e3807dd1eef70181e15f97b00054fd46a9b

test:
  secret_key_base: 0762d8f193470eb421e80aedb2b2ba784482dc81dd7d322114ab4cb6fad459688c16669946b378e7f152d9186a7d448450547f48f39a43eee2afe8c4b2df8a48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
